#!/bin/sh
#
# Starts docker daemon.
#

start() {
	printf "Starting dockerd daemon: "
	umask 077

	start-stop-daemon -S -q -b -p /var/run/dockerd.pid \
		--exec /usr/bin/dockerd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping dockerd daemon: "
	start-stop-daemon -K -q -p /var/run/dockerd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

